services:
  web:
    build:
      context: build
      target: builder
    container_name: "MAZJOHN-HTML"
    ports: 
      - '127.0.0.1:2020:80'
    volumes:
      - ./html:/usr/local/apache2/htdocs
      - ./config:/usr/local/apache2/conf